# Generated by Django 2.1.5 on 2019-01-08 21:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnumb', models.CharField(max_length=25, verbose_name='№ рейса')),
                ('flighymodel', models.CharField(max_length=50, verbose_name='Модель самолета')),
                ('flightfrom', models.CharField(max_length=25, verbose_name='Откуда')),
                ('flightto', models.CharField(max_length=25, verbose_name='Куда')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание рейса')),
                ('photo', models.ImageField(default='../static/images/not_found2.jpg', upload_to='flights/%Y', verbose_name='Картинка рейса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена перелета')),
                ('active', models.BooleanField(default=True, verbose_name='Рейс активен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('bookings', models.ManyToManyField(blank=True, related_name='flight_booking', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_created', to=settings.AUTH_USER_MODEL, verbose_name='Перевозчик')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ('-updated',),
            },
        ),
    ]
